/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ce103.hw6.calc.app.java;

import java.rmi.server.Operation;

/**
 *
 * @author Furkan Ayakdaş
 */
public class Calculator extends javax.swing.JFrame implements Calculations{
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bracket1 = new javax.swing.JButton();
        bracket2 = new javax.swing.JButton();
        backspace = new javax.swing.JButton();
        off = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        ebutton = new javax.swing.JButton();
        PI = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        arcsin = new javax.swing.JButton();
        arccos = new javax.swing.JButton();
        arctan = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        xfactorial = new javax.swing.JButton();
        four = new javax.swing.JButton();
        one = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        five = new javax.swing.JButton();
        two = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        six = new javax.swing.JButton();
        three = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        multiplication = new javax.swing.JButton();
        subtraction = new javax.swing.JButton();
        addition = new javax.swing.JButton();
        xsqrt2 = new javax.swing.JButton();
        ansbutton = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        nPrbutton = new javax.swing.JButton();
        nCrbutton = new javax.swing.JButton();
        xsqrty = new javax.swing.JButton();
        xsqrt3 = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        oneoverx = new javax.swing.JButton();
        lnx = new javax.swing.JButton();
        logx = new javax.swing.JButton();
        processingarea = new javax.swing.JTextField();
        appname = new javax.swing.JLabel();
        resultarea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        bracket1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bracket1.setText("(");
        bracket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracket1ActionPerformed(evt);
            }
        });

        bracket2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bracket2.setText(")");
        bracket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bracket2ActionPerformed(evt);
            }
        });

        backspace.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backspace.setForeground(new java.awt.Color(0, 0, 255));
        backspace.setText("Backspace");
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });

        off.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        off.setForeground(new java.awt.Color(255, 0, 0));
        off.setText("OFF");
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        clearbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(0, 0, 255));
        clearbutton.setText("CE");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        ebutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ebutton.setText("e");
        ebutton.setToolTipText("");
        ebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebuttonActionPerformed(evt);
            }
        });

        PI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PI.setText("PI");
        PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIActionPerformed(evt);
            }
        });

        seven.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        sin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sin.setForeground(new java.awt.Color(0, 204, 102));
        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        cos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cos.setForeground(new java.awt.Color(0, 204, 102));
        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        tan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tan.setForeground(new java.awt.Color(0, 204, 102));
        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        arcsin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        arcsin.setForeground(new java.awt.Color(0, 204, 102));
        arcsin.setText("sin-1");
        arcsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcsinActionPerformed(evt);
            }
        });

        arccos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        arccos.setForeground(new java.awt.Color(0, 204, 102));
        arccos.setText("cos-1");
        arccos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arccosActionPerformed(evt);
            }
        });

        arctan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        arctan.setForeground(new java.awt.Color(0, 204, 102));
        arctan.setText("tan-1");
        arctan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arctanActionPerformed(evt);
            }
        });

        nine.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        divide.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        divide.setForeground(new java.awt.Color(255, 153, 0));
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        xfactorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xfactorial.setForeground(new java.awt.Color(255, 51, 51));
        xfactorial.setText("x!");
        xfactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xfactorialActionPerformed(evt);
            }
        });

        four.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        one.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        zero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        five.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        two.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        dot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        six.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        three.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        equal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        equal.setForeground(new java.awt.Color(204, 0, 204));
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        multiplication.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        multiplication.setForeground(new java.awt.Color(255, 153, 0));
        multiplication.setText("*");
        multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationActionPerformed(evt);
            }
        });

        subtraction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subtraction.setForeground(new java.awt.Color(255, 153, 0));
        subtraction.setText("-");
        subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionActionPerformed(evt);
            }
        });

        addition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addition.setForeground(new java.awt.Color(255, 153, 0));
        addition.setText("+");
        addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionActionPerformed(evt);
            }
        });

        xsqrt2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xsqrt2.setForeground(new java.awt.Color(255, 51, 51));
        xsqrt2.setText("x^2");
        xsqrt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xsqrt2ActionPerformed(evt);
            }
        });

        ansbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ansbutton.setForeground(new java.awt.Color(0, 0, 255));
        ansbutton.setText("Ans");
        ansbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansbuttonActionPerformed(evt);
            }
        });

        sqrt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sqrt.setForeground(new java.awt.Color(0, 204, 102));
        sqrt.setText("sqrt");
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });

        nPrbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nPrbutton.setForeground(new java.awt.Color(255, 51, 51));
        nPrbutton.setText("nPr");
        nPrbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPrbuttonActionPerformed(evt);
            }
        });

        nCrbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nCrbutton.setForeground(new java.awt.Color(255, 51, 51));
        nCrbutton.setText("nCr");
        nCrbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nCrbuttonActionPerformed(evt);
            }
        });

        xsqrty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xsqrty.setForeground(new java.awt.Color(255, 51, 51));
        xsqrty.setText("x^y");
        xsqrty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xsqrtyActionPerformed(evt);
            }
        });

        xsqrt3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xsqrt3.setForeground(new java.awt.Color(255, 51, 51));
        xsqrt3.setText("x^3");
        xsqrt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xsqrt3ActionPerformed(evt);
            }
        });

        mod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mod.setForeground(new java.awt.Color(255, 51, 51));
        mod.setText("%");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });

        oneoverx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        oneoverx.setForeground(new java.awt.Color(255, 51, 51));
        oneoverx.setText("1/x");
        oneoverx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneoverxActionPerformed(evt);
            }
        });

        lnx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lnx.setForeground(new java.awt.Color(0, 204, 102));
        lnx.setText("ln x");
        lnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnxActionPerformed(evt);
            }
        });

        logx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logx.setForeground(new java.awt.Color(0, 204, 102));
        logx.setText("log x");
        logx.setToolTipText("");
        logx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logxActionPerformed(evt);
            }
        });

        processingarea.setEditable(false);
        processingarea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        processingarea.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        processingarea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        processingarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processingareaActionPerformed(evt);
            }
        });

        appname.setFont(new java.awt.Font("Segoe UI Light", 2, 36)); // NOI18N
        appname.setText(" Scientific Calculator");

        resultarea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resultarea.setForeground(new java.awt.Color(0, 204, 51));
        resultarea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(appname)
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(off, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bracket1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bracket2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clearbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(ebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(zero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(one, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(four, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sin, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(eight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(two, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cos, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(six, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(three, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tan, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(multiplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subtraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(arcsin, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(xfactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xsqrt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ansbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sqrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(arccos, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(nPrbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xsqrt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lnx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(arctan, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(nCrbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xsqrty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(oneoverx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(logx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(2, 2, 2))
                            .addComponent(resultarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(processingarea))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bracket1)
                        .addComponent(bracket2))
                    .addComponent(processingarea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(resultarea, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(arcsin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(arccos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(arctan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(5, 5, 5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seven, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(eight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xfactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nPrbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nCrbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clearbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(four, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(five, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(six, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multiplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xsqrt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xsqrt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xsqrty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ansbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oneoverx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addition, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lnx, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(logx, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(off, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        //we printed 7 on the screen
        processingarea.setText(processingarea.getText() + "7");
    }//GEN-LAST:event_sevenActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        //we printed 0 on the screen
        processingarea.setText(processingarea.getText() + "0");
    }//GEN-LAST:event_zeroActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        //we printed 2 on the screen
        processingarea.setText(processingarea.getText() + "2");
    }//GEN-LAST:event_twoActionPerformed

    private void processingareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processingareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processingareaActionPerformed

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        //we defined the value
        String value = processingarea.getText();
        //we defined the length value
        int length = value.length();
        
        //we started the loop
        if(length>0){
            
            //we created the new object
            StringBuilder builder = new StringBuilder(value);
            //we deleted one char
            builder.deleteCharAt(length-1);
            //we printed new length on the screen
            processingarea.setText(builder.toString());
        }
    }//GEN-LAST:event_backspaceActionPerformed

    private void bracket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracket1ActionPerformed
        //we printed ( on the screen
        processingarea.setText(processingarea.getText() + "(");
    }//GEN-LAST:event_bracket1ActionPerformed

    private void bracket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bracket2ActionPerformed
        //we printed ) on the screen
        processingarea.setText(processingarea.getText() + ")");
    }//GEN-LAST:event_bracket2ActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        //OFF button code
        this.setVisible(false);
    }//GEN-LAST:event_offActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        //we cleared the screen
        processingarea.setText(null);
        //we cleared the screen
        resultarea.setText(null);  
    }//GEN-LAST:event_clearbuttonActionPerformed
 
    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        //we printed 4 on the screen
        processingarea.setText(processingarea.getText() + "4");
    }//GEN-LAST:event_fourActionPerformed

    private void ebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebuttonActionPerformed
        //we defined the ops value
        double ops;
        //we equated e value to ops
        ops = Math.E;
        //we printed e value on the screen
        processingarea.setText(String.valueOf(ops));
    }//GEN-LAST:event_ebuttonActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        //we printed 1 on the screen
        processingarea.setText(processingarea.getText() + "1");
    }//GEN-LAST:event_oneActionPerformed

    private void PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIActionPerformed
        //we defined the ops value
        double ops;
        //we equated PI value to ops
        ops = Math.PI;
        //we printed PI value on the screen
        processingarea.setText(String.valueOf(ops));
    }//GEN-LAST:event_PIActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        //we defined the ops value
        double ops = Double.parseDouble(String.valueOf(processingarea.getText()));
        //we equated sin value to ops
        ops = Math.sin(ops);
        //we printed sin value on the screen
        processingarea.setText(String.valueOf(ops));
    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        //we defined the ops value
        double ops = Double.parseDouble(String.valueOf(processingarea.getText()));
        //we equated cos value to ops
        ops = Math.cos(ops);
        //we printed cos value on the screen
        processingarea.setText(String.valueOf(ops));
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        //we defined the ops value
        double ops = Double.parseDouble(String.valueOf(processingarea.getText()));
        //we equated tan value to ops
        ops = Math.tan(ops);
        //we printed tan value on the screen
        processingarea.setText(String.valueOf(ops));
    }//GEN-LAST:event_tanActionPerformed

    private void arcsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcsinActionPerformed
        //we defined the ops value
        double ops = Double.parseDouble(String.valueOf(processingarea.getText()));
        //we equated asin value to ops
        ops = Math.asin(ops);
        //we printed asin value on the screen
        processingarea.setText(String.valueOf(ops));
    }//GEN-LAST:event_arcsinActionPerformed

    private void arccosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arccosActionPerformed
        //We defiend the ops value
        double ops = Double.parseDouble(String.valueOf(processingarea.getText()));
        //we equated acos value to ops
        ops = Math.acos(ops);
        //we printed acos value on the screen
        processingarea.setText(String.valueOf(ops));
    }//GEN-LAST:event_arccosActionPerformed

    private void arctanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arctanActionPerformed
        //we defined the ops value
        double ops = Double.parseDouble(String.valueOf(processingarea.getText()));
        //we equated atan value to ops
        ops = Math.atan(ops);
        //we printed atan value on the screen
        processingarea.setText(String.valueOf(ops));
    }//GEN-LAST:event_arctanActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        //we printed 8 on the screen
        processingarea.setText(processingarea.getText() + "8");
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        //we printed 9 on the screen
        processingarea.setText(processingarea.getText() + "9");
    }//GEN-LAST:event_nineActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        
        //we defined the sign value
        sign = "/";
        //we started the loop
        if(processingarea.getText().length()>0)
        //we call the function
        storeToBeCalculatedValue(sign);
        
    }//GEN-LAST:event_divideActionPerformed

    private void xfactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xfactorialActionPerformed
        
        //we defined the i value
        double i;
        //we defined the fact value
        int fact = 1;
        //we defined the toBeCalculatedValue value
        toBeCalculatedValue = Double.parseDouble(processingarea.getText());
        //we started the loop
        for(i = toBeCalculatedValue; i>=1; i--)
        {
            //we equated fact*i value to fact
            fact *= i;
        }
        //we printed fact value on the screen
        processingarea.setText(Integer.toString(fact));
 
    }//GEN-LAST:event_xfactorialActionPerformed

    private void nPrbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPrbuttonActionPerformed
        //we printed P on the screen
        processingarea.setText(processingarea.getText() + "P");
    }//GEN-LAST:event_nPrbuttonActionPerformed

    private void nCrbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nCrbuttonActionPerformed
        //we printed C on the screen
        processingarea.setText(processingarea.getText() + "C");
    }//GEN-LAST:event_nCrbuttonActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        //we printed 5 on the screen
        processingarea.setText(processingarea.getText() + "5");
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        //we printed 6 on the screen
        processingarea.setText(processingarea.getText() + "6");
    }//GEN-LAST:event_sixActionPerformed

    private void multiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationActionPerformed
        
        //we defined the sign value
        sign = "*";
        //we started the loop
        if(processingarea.getText().length()>0)
        //we call the function
        storeToBeCalculatedValue(sign);
    }//GEN-LAST:event_multiplicationActionPerformed

    private void xsqrt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xsqrt2ActionPerformed
        
        //we started the loop
        if(processingarea.getText().length()>0){
        //we defined the toBeCalculatedValue value
        toBeCalculatedValue = Double.parseDouble(processingarea.getText());
        //we call the function
        square(toBeCalculatedValue);
        }
    }//GEN-LAST:event_xsqrt2ActionPerformed

    private void square(double a){
        //we printed x^2 on the screen
        processingarea.setText(Double.toString(a*=a));
    }
    
    private void xsqrt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xsqrt3ActionPerformed
        //we started the loop
        if(processingarea.getText().length()>0){
        //we defined the toBeCalculatedValue value
        toBeCalculatedValue = Double.parseDouble(processingarea.getText());
        //we call the function
        cube(toBeCalculatedValue);
        }
    }//GEN-LAST:event_xsqrt3ActionPerformed

    private void cube(double a){
        //we printed x^3 on the screen
        processingarea.setText(Double.toString(a*=a*a));
    }
        
    private void xsqrtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xsqrtyActionPerformed
        //we defined the sign value
        sign = "^";
        //we started the loop
        if(processingarea.getText().length()>0)
        //we call the function
        storeToBeCalculatedValue(sign);
    }//GEN-LAST:event_xsqrtyActionPerformed
    
    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        //we printed 3 on the screen
        processingarea.setText(processingarea.getText() + "3");
    }//GEN-LAST:event_threeActionPerformed

    private void subtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionActionPerformed
        //we defined the sign value
        sign = "-";
        //we started the loop
        if(processingarea.getText().length()>0)
        //we call the function
        storeToBeCalculatedValue(sign);
    }//GEN-LAST:event_subtractionActionPerformed

    private void ansbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansbuttonActionPerformed

        //we defined ans value
        String ans;
        //we defined ans value
        ans = resultarea.getText();
        //we writed the ans value
        resultarea.setText(ans + resultarea.getText());
    }//GEN-LAST:event_ansbuttonActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        //we defined the sign value
        sign = "%";
        //we started the loop
        if(processingarea.getText().length()>0)
        //we call the function
        storeToBeCalculatedValue(sign);   
        
    }//GEN-LAST:event_modActionPerformed

    private void oneoverxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneoverxActionPerformed
        //we defined the a value
        double a = 1/(Double.parseDouble(processingarea.getText()));
        //we printed blank on the screen
        processingarea.setText("");
        //we printed 1/x on the screen
        processingarea.setText(processingarea.getText()+a);
    }//GEN-LAST:event_oneoverxActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        //we started the loop
        if(!isDecimal){
        //we printed the . on the screen
        processingarea.setText(processingarea.getText() + ".");
        //we defined the isDecimal value
        isDecimal = true;
        }
    }//GEN-LAST:event_dotActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
       
        //we started the loop
        if (processingarea.getText().length()>0){
            
            //we defined the b value
            double b = Double.parseDouble(processingarea.getText());    
        
        //we started the switch-case    
        switch(sign){
            
            case "+":
            //we call the function
            add(toBeCalculatedValue, b);
            break;
            
            case "-":
            //we call the function
            substract(toBeCalculatedValue, b);
            break;
            
            case "*":
            //we call the function    
            multiply(toBeCalculatedValue, b);
            break;
            
            case "/":
            //we call the function
            divide(toBeCalculatedValue, b);
            break;
            
            case "%":
            //we call the function
            mod(toBeCalculatedValue, b);
            break;
           
            case "^":
            //we call the function
            xsqrty(toBeCalculatedValue, b);
            break;
        
        }
        }
    }//GEN-LAST:event_equalActionPerformed

    private void additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionActionPerformed
        //we defined the sign value
        sign = "+";
        //we started the loop
        if(processingarea.getText().length()>0)
        //we call the function
        storeToBeCalculatedValue(sign);
    }//GEN-LAST:event_additionActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed

        //we defined the toBeCalculatedValue
        toBeCalculatedValue = Double.parseDouble(processingarea.getText());
        //we call the function
        sqrRoot(toBeCalculatedValue);
    }//GEN-LAST:event_sqrtActionPerformed
    
    private void sqrRoot(double a){
        //we printed sqrt on the screen
        processingarea.setText(Double.toString(Math.sqrt(a)));
    
    }
    
    private void lnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnxActionPerformed
        //we defined the ops value
        double ops = Double.parseDouble(String.valueOf(processingarea.getText()));
        //we equated log value to ops
        ops = Math.log(ops);
        //we printed log value on the screen
        processingarea.setText(String.valueOf(ops));
    }//GEN-LAST:event_lnxActionPerformed

    private void logxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logxActionPerformed
        //we defined the ops value
        double ops = Double.parseDouble(String.valueOf(processingarea.getText()));
        //we equated log10 value to ops
        ops = Math.log10(ops);
        //we printed log10 value on the screen
        processingarea.setText(String.valueOf(ops));
    }//GEN-LAST:event_logxActionPerformed

    @Override
    public void add(double a, double b){
        //has been returned
        setResult(a+b);
     }

    @Override
    public void substract(double a, double b) {
        //has been returned
        setResult(a-b);
    }

    @Override
    public void multiply(double a, double b) {
        //has been returned
        setResult(a*b);
    }

    @Override
    public void divide(double a, double b) {
        //has been returned
        setResult(a/b);
    }
    
    @Override
    public void mod(double a, double b){
        //has been returned
        setResult(a%b);
    }
    
    @Override
    public void xsqrty(double a, double b){
        //has been returned
        setResult(Math.pow(a, b));
    }
       
    private void setResult(double result){
    
        //we printed result on the screen
        processingarea.setText(Double.toString(result));
        //we printed blank on the screen
        resultarea.setText("");
        
    }
    
    private void storeToBeCalculatedValue(String sign){
    
        //we defined the value 
        String value = processingarea.getText();
        //we defined the toBeCalculatedValue value
        toBeCalculatedValue = Double.parseDouble(value);
    
        //we printed value+blank+sign on the screen
        resultarea.setText(value + "" + sign);
        //we printed blank on the screen
        processingarea.setText("");
    
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    //we defined the firstnum
    double firstnum;
    //we defined the secondnum
    double secondnum;
    //we defined the result
    double result;
    //we defined the sign
    private String sign;
    //we defined the isDecimal
    private boolean isDecimal = false;
    //we defined the toBeCalculatedValue
    private double toBeCalculatedValue;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PI;
    private javax.swing.JButton addition;
    private javax.swing.JButton ansbutton;
    private javax.swing.JLabel appname;
    private javax.swing.JButton arccos;
    private javax.swing.JButton arcsin;
    private javax.swing.JButton arctan;
    private javax.swing.JButton backspace;
    private javax.swing.JButton bracket1;
    private javax.swing.JButton bracket2;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton cos;
    private javax.swing.JButton divide;
    private javax.swing.JButton dot;
    private javax.swing.JButton ebutton;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton lnx;
    private javax.swing.JButton logx;
    private javax.swing.JButton mod;
    private javax.swing.JButton multiplication;
    private javax.swing.JButton nCrbutton;
    private javax.swing.JButton nPrbutton;
    private javax.swing.JButton nine;
    private javax.swing.JButton off;
    private javax.swing.JButton one;
    private javax.swing.JButton oneoverx;
    private javax.swing.JTextField processingarea;
    private javax.swing.JLabel resultarea;
    private javax.swing.JButton seven;
    private javax.swing.JButton sin;
    private javax.swing.JButton six;
    private javax.swing.JButton sqrt;
    private javax.swing.JButton subtraction;
    private javax.swing.JButton tan;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton xfactorial;
    private javax.swing.JButton xsqrt2;
    private javax.swing.JButton xsqrt3;
    private javax.swing.JButton xsqrty;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}